const animalNames = [
  'alligator',
  'anteater',
  'armadillo',
  'auroch',
  'axolotl',
  'badger',
  'bat',
  'beaver',
  'buffalo',
  'camel',
  'capybara',
  'chameleon',
  'cheetah',
  'chinchilla',
  'chipmunk',
  'chupacabra',
  'cormorant',
  'coyote',
  'crow',
  'dingo',
  'dinosaur',
  'dolphin',
  'duck',
  'elephant',
]

const adjectives = [
  'adorable',
  'adventurous',
  'aggressive',
  'agreeable',
  'alert',
  'alive',
  'amused',
  'angry',
  'annoyed',
  'annoying',
  'anxious',
  'arrogant',
  'ashamed',
  'attractive',
  'faithful',
  'famous',
  'fancy',
  'fantastic',
  'fierce',
  'filthy',
  'boiling',
  'tasty',
  'tender',
  'tough',
]

const colours = [
  'red',
  'orange',
  'yellow',
  'green',
  'blue',
  'purple',
  'grey',
  'white',
  'black',
  'pink',
  'brown',
]

export function generateUserName() {
  return `${adjectives[Math.floor(Math.random() * adjectives.length)]}-${colours[Math.floor(Math.random() * colours.length)]}-${animalNames[Math.floor(Math.random() * animalNames.length)]}`
}